version: '3.8'

services:
  db:
    build:
      context: ./db
    env_file:
      - ../.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:cached
      - ./db/data:/var/lib/mysql:cached

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    # To develop as current user on Linux (e.g. 1000:1000 ... $(id -u):$(id -g))
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ..:/var/www:consistent

  nginx:
    build:
      context: ./nginx
    volumes:
      - ..:/var/www:consistent
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./nginx/sites/:/etc/nginx/sites-available:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d:cached
      - ./logs/nginx:/var/log/nginx:cached
    depends_on:
      - php-fpm
    ports:
      - 8000:80
